### ISSUE TITLE
Rotation des Spielfelds dämpfen

### ISSUE THREAD

**Issue by lenalinke** [rwth-acis/MixedRealityTiltMaze-StackOfQueues#14]
Ziel: Ball sollte nicht mehr durch den Boden fallen bei abrupten Bewegungen
- [ ] Ersetzen der Stelle, wo direkt die neue Zielrotation dem Transform zuweisen wird gegen eine Interpolation die die aktuelle Spielfeld-Rotation ausliest und mit einer gegebenen Schrittweite zur Zielrotation interpoliert
  -Da die Berechnung in jedem Frame durchgeführt wird, nähert sich so die Rotation des Spielfelds dem Zielwert an
- [ ] Schrittweite soll im Inspektor anpassbar sein
    - Die Quaternion-Klasse bietet für Interpolationen die Slerp Funktion
- [ ] von Framerate unabhängige Schrittweite
   - bei Interpolation die Schrittweite mit Time.deltaTime1 multiplizieren
   - Dieser Wert gibt den Abstand vom letzten Frame zum aktuellen in Sekunden an. Die Schrittweite
beschreibt dann also die Schrittweite pro Sekunde und nicht pro Frame

Aufgabe 2.2 d)

**Comment by anreji** [comment]
Duplicate of #12
